/*create database db_exampleName;
*/

CREATE TABLE PERSONA
(
DNI VARCHAR(9) NOT NULL,
NOMBRE VARCHAR(15) NOT NULL,
APELLIDOS VARCHAR(20) NOT NULL,
CONSTRAINT PK_PERSONA PRIMARY KEY (DNI)
);

CREATE TABLE JUGADOR
(
DNI VARCHAR(9) NOT NULL,
EDAD INT(2),
SALDO INT(5),
ANIO_REGISTRO DATE,
CONSTRAINT PK_JUGADOR PRIMARY KEY (DNI),
CONSTRAINT FK_JUGADOR FOREIGN KEY (DNI) REFERENCES PERSONA (DNI)

);


CREATE TABLE MESA 
(
COD_MESA INT(2) NOT NULL,
UBICACION VARCHAR(15),
TIPO VARCHAR(12),
CAPACIDAD INT(2),
CONSTRAINT PK_MESA PRIMARY KEY (COD_MESA)
);


CREATE TABLE CRUPIER
(
DNI VARCHAR(9) NOT NULL,
TURNO INT(2) NOT NULL,
EXP_CRUPIER VARCHAR(12),
COD_MESA INT(2) NOT NULL,
CONSTRAINT PK_CRUPIER PRIMARY KEY (DNI),
CONSTRAINT FK1_CRUPIER FOREIGN KEY (DNI) REFERENCES PERSONA (DNI),
CONSTRAINT FK2_CRUPIER FOREIGN KEY (COD_MESA) REFERENCES MESA (COD_MESA)
);



CREATE TABLE BARAJA
(
REF_BARAJA INT(2) NOT NULL,
NUM_CARTAS INT(2),
CONSTRAINT PK_BARAJA PRIMARY KEY (REF_BARAJA)
);



CREATE TABLE RESULTADO
(
CLAVE VARCHAR(10) NOT NULL,
TIPO VARCHAR(12) NOT NULL,
GANANCIA INT(5) NOT NULL,
CONSTRAINT PK_RESULTADO PRIMARY KEY (CLAVE)
);


CREATE TABLE PARTIDA
(
NUM_PARTIDA INT(2) NOT NULL,
FECHA_PARTIDA DATE,
REF_BARAJA INT(2) NOT NULL,
CLAVE_RESULTADO VARCHAR(10) NOT NULL,
CONSTRAINT PK_PARTIDA PRIMARY KEY (NUM_PARTIDA),
CONSTRAINT FK1_PARTIDA FOREIGN KEY (REF_BARAJA) REFERENCES BARAJA (REF_BARAJA),
CONSTRAINT FK2_PARTIDA FOREIGN KEY (CLAVE_RESULTADO) REFERENCES RESULTADO (CLAVE)
);

CREATE TABLE JUEGA
(
DNI VARCHAR(9) NOT NULL,
NUM_PARTIDA INT(2) NOT NULL,
CONSTRAINT PK_JUEGA PRIMARY KEY (DNI)
);

CREATE TABLE MANO
(
COD_MANO VARCHAR(10) NOT NULL,
ESTADO VARCHAR(12),
PUNTAJE INT(3),
CONSTRAINT PK_MANO PRIMARY KEY (COD_MANO)
);



CREATE TABLE CARTAS
(
REF_BARAJA INT(2) NOT NULL,
COD_MANO VARCHAR(10) NOT NULL,
VALOR_CARTA INT(2) NOT NULL,
CONSTRAINT PK_CARTAS PRIMARY KEY (REF_BARAJA, COD_MANO, VALOR_CARTA),
CONSTRAINT FK1_CARTAS FOREIGN KEY(COD_MANO) REFERENCES MANO (COD_MANO),
CONSTRAINT FK2_CARTAS FOREIGN KEY(REF_BARAJA) REFERENCES BARAJA (REF_BARAJA)
);

CREATE TABLE APUESTA
(
NUM_APUESTA INT(2) NOT NULL,
MONTO INT(5),
CLAVE_RESULTADO VARCHAR(10) NOT NULL,
COD_MANO VARCHAR(10) NOT NULL,
CONSTRAINT PK_APUESTA PRIMARY KEY (NUM_APUESTA),
CONSTRAINT FK1_APUESTA FOREIGN KEY (CLAVE_RESULTADO) REFERENCES RESULTADO (CLAVE),
CONSTRAINT FK2_APUESTA FOREIGN KEY (COD_MANO) REFERENCES MANO (COD_MANO)
);




CREATE TABLE REALIZA
(
NUM_APUESTA INT(2) NOT NULL,
DNI VARCHAR(9) NOT NULL,
CONSTRAINT PK_REALIZA PRIMARY KEY (NUM_APUESTA, DNI),
CONSTRAINT FK1_REALIZA FOREIGN KEY (NUM_APUESTA) REFERENCES APUESTA (NUM_APUESTA),
CONSTRAINT FK2_REALIZA FOREIGN KEY (DNI) REFERENCES JUGADOR (DNI) 
);


CREATE TABLE ESTADISTICAS
(
NUM_REG_ESTADISTICAS INT(3),
DNI VARCHAR(9),
CONSTRAINT PK_ESTADISTICAS PRIMARY KEY (NUM_REG_ESTADISTICAS),
CONSTRAINT FK_ESTADISTICAS FOREIGN KEY (DNI) REFERENCES JUGADOR (DNI)
);


