/*alter session set "_oracle_script"=true;  
create user bol1-ej3 identified by bol1-ej3;
GRANT CONNECT, RESOURCE, DBA TO bol1-ej3;
*/





CREATE TABLE PERSONA
(
DNI VARCHAR2(9) NOT NULL,
NOMBRE VARCHAR2(15) NOT NULL,
APELLIDOS VARCHAR2(20) NOT NULL,
CONSTRAINT PK_PERSONA PRIMARY KEY (DNI)
);

CREATE TABLE JUGADOR
(
DNI VARCHAR2(9) NOT NULL,
EDAD NUMBER(2),
SALDO NUMBER(5,2),
ANIO_REGISTRO DATE,
CONSTRAINT PK_JUGADOR PRIMARY KEY (DNI),
CONSTRAINT FK_JUGADOR FOREIGN KEY (DNI) REFERENCES PERSONA (DNI)

);


CREATE TABLE MESA 
(
COD_MESA NUMBER(2) NOT NULL,
UBICACION VARCHAR2(15),
TIPO VARCHAR2(12),
CAPACIDAD NUMBER(2),
CONSTRAINT PK_MESA PRIMARY KEY (COD_MESA)
);


CREATE TABLE CRUPIER
(
DNI VARCHAR2(9) NOT NULL,
TURNO NUMBER(2) NOT NULL,
EXP_CRUPIER VARCHAR2(12),
COD_MESA NUMBER(2) NOT NULL,
CONSTRAINT PK_CRUPIER PRIMARY KEY (DNI),
CONSTRAINT FK1_CRUPIER FOREIGN KEY (DNI) REFERENCES PERSONA (DNI),
CONSTRAINT FK2_CRUPIER FOREIGN KEY (COD_MESA) REFERENCES MESA (COD_MESA)
);



CREATE TABLE BARAJA
(
REF_BARAJA NUMBER(2) NOT NULL,
NUM_CARTAS NUMBER(2),
CONSTRAINT PK_BARAJA PRIMARY KEY (REF_BARAJA)
);



CREATE TABLE RESULTADO
(
CLAVE VARCHAR2(10) NOT NULL,
TIPO VARCHAR2(12) NOT NULL,
GANANCIA NUMBER(5,2) NOT NULL,
CONSTRAINT PK_RESULTADO PRIMARY KEY (CLAVE)
);


CREATE TABLE PARTIDA
(
NUM_PARTIDA NUMBER(2) NOT NULL,
FECHA_PARTIDA DATE,
REF_BARAJA NUMBER(2) NOT NULL,
CLAVE_RESULTADO VARCHAR2(10) NOT NULL,
CONSTRAINT PK_PARTIDA PRIMARY KEY (NUM_PARTIDA),
CONSTRAINT FK1_PARTIDA FOREIGN KEY (REF_BARAJA) REFERENCES BARAJA (REF_BARAJA),
CONSTRAINT FK2_PARTIDA FOREIGN KEY (CLAVE_RESULTADO) REFERENCES RESULTADO (CLAVE)
);

CREATE TABLE JUEGA
(
DNI VARCHAR2(9) NOT NULL,
NUM_PARTIDA NUMBER(2) NOT NULL,
CONSTRAINT PK_JUEGA PRIMARY KEY (DNI)
);

CREATE TABLE MANO
(
COD_MANO VARCHAR2(10) NOT NULL,
ESTADO VARCHAR2(12),
PUNTAJE NUMBER(3),
CONSTRAINT PK_MANO PRIMARY KEY (COD_MANO)
);



CREATE TABLE CARTAS
(
REF_BARAJA NUMBER(2) NOT NULL,
COD_MANO VARCHAR2(10) NOT NULL,
VALOR_CARTA NUMBER(2) NOT NULL,
CONSTRAINT PK_CARTAS PRIMARY KEY (REF_BARAJA, COD_MANO, VALOR_CARTA),
CONSTRAINT FK1_CARTAS FOREIGN KEY(COD_MANO) REFERENCES MANO (COD_MANO),
CONSTRAINT FK2_CARTAS FOREIGN KEY(REF_BARAJA) REFERENCES BARAJA (REF_BARAJA)
);

CREATE TABLE APUESTA
(
NUM_APUESTA NUMBER(2) NOT NULL,
MONTO NUMBER(5,2),
CLAVE_RESULTADO VARCHAR2(10) NOT NULL,
COD_MANO VARCHAR2(10) NOT NULL,
CONSTRAINT PK_APUESTA PRIMARY KEY (NUM_APUESTA),
CONSTRAINT FK1_APUESTA FOREIGN KEY (CLAVE_RESULTADO) REFERENCES RESULTADO (CLAVE),
CONSTRAINT FK2_APUESTA FOREIGN KEY (COD_MANO) REFERENCES MANO (COD_MANO)
);




CREATE TABLE REALIZA
(
NUM_APUESTA NUMBER(2) NOT NULL,
DNI VARCHAR2(9) NOT NULL,
CONSTRAINT PK_REALIZA PRIMARY KEY (NUM_APUESTA, DNI),
CONSTRAINT FK1_REALIZA FOREIGN KEY (NUM_APUESTA) REFERENCES APUESTA (NUM_APUESTA),
CONSTRAINT FK2_REALIZA FOREIGN KEY (DNI) REFERENCES JUGADOR (DNI) 
);


CREATE TABLE ESTADISTICAS
(
NUM_REG_ESTADISTICAS NUMBER(3),
DNI VARCHAR2(9),
CONSTRAINT PK_ESTADISTICAS PRIMARY KEY (NUM_REG_ESTADISTICAS),
CONSTRAINT FK_ESTADISTICAS FOREIGN KEY (DNI) REFERENCES JUGADOR (DNI)
);



