create database bbdd_usuario

CREATE TABLE PERSONA (
DNI VARCHAR (10) NOT NULL,
NOMBRE VARCHAR (10),
APELLIDOS VARCHAR (10),
CONSTRAINT PK_DNI PRIMARY KEY (DNI)
);

CREATE TABLE JUGADOR (
DNI VARCHAR (10),
EDAD INT (10),
SALDO INT (10),
ANIO_REGISTRO DATE,
CONSTRAINT PK_JUGADOR PRIMARY KEY (DNI),
CONSTRAINT FK1_JUGADOR FOREIGN KEY (DNI) REFERENCES PERSONA(DNI)
);

CREATE TABLE MESA (
COD_MESA INT (10) NOT NULL,
UBICACION VARCHAR(10),
TIPO VARCHAR(10),
CAPACIDAD INT(10),
CONSTRAINT PK_MESA PRIMARY KEY (COD_MESA)
);

CREATE TABLE CRUPIER (
DNI VARCHAR(10),
TURNO INT (10),
EXP_CRUPIER VARCHAR(10),
COD_MESA INT(10),
CONSTRAINT PK_CRUPIER PRIMARY KEY (DNI),
CONSTRAINT FKCRUPIER1 FOREIGN KEY (DNI) REFERENCES PERSONA(DNI),
CONSTRAINT FKCRUPIER2 FOREIGN KEY (COD_MESA) REFERENCES MESA(COD_MESA)
);

CREATE TABLE BARAJA (
REF_BARAJA INT(10),
NUM_CARTAS INT (10),
CONSTRAINT PK_BARAJA PRIMARY KEY (REF_BARAJA)
);

CREATE TABLE RESULTADO (
CLAVE VARCHAR(10) NOT NULL,
TIPO VARCHAR(10),
GANANCIA INT(10) NOT NULL,
CONSTRAINT PK_RESULTADO PRIMARY KEY (CLAVE)
);

CREATE TABLE PARTIDA (
NUM_PARTIDA INT(10) NOT NULL,
FECHA_PARTIDA DATE,
REF_BARAJA INT(10) NOT NULL,
CLAVE_RESULTADO VARCHAR(10) NOT NULL,
CONSTRAINT PK_PARTIDA PRIMARY KEY (NUM_PARTIDA),
CONSTRAINT FK1_PARTIDA FOREIGN KEY (REF_BARAJA) REFERENCES BARAJA(REF_BARAJA),
CONSTRAINT FK2_PARTIDA FOREIGN KEY (CLAVE_RESULTADO) REFERENCES RESULTADO(CLAVE)
);

CREATE TABLE JUEGA (
DNI VARCHAR(10) NOT NULL,
NUM_PARTIDA INT(10),
CONSTRAINT PK_JUEGA PRIMARY KEY (DNI,NUM_PARTIDA),
CONSTRAINT FK_JUEGA1 FOREIGN KEY (DNI) REFERENCES PERSONA(DNI),
CONSTRAINT FK_JUEGA2 FOREIGN KEY (NUM_PARTIDA) REFERENCES PARTIDA(NUM_PARTIDA)

);

CREATE TABLE MANO (
COD_MANO INT(10),
ESTADO VARCHAR(10),
PUNTAJE INT(10),
CONSTRAINT PK_MANO PRIMARY KEY (COD_MANO)
);

CREATE TABLE CARTAS (
REF_BARAJA INT(10) NOT NULL,
COD_MANO INT(10),
VALOR_CARTA INT(10),
CONSTRAINT PK_CARTAS PRIMARY KEY (REF_BARAJA,COD_MANO,VALOR_CARTA),
CONSTRAINT FK1_CARTAS FOREIGN KEY (REF_BARAJA) REFERENCES BARAJA(REF_BARAJA),
CONSTRAINT FK2_CARTAS FOREIGN KEY (COD_MANO) REFERENCES MANO(COD_MANO)
);

CREATE TABLE APUESTA (
NUM_APUESTA INT(10) NOT NULL,
MONTO INT(10),
CLAVE_RESULTADO VARCHAR(10),
COD_MANO INT(10),
CONSTRAINT PK_APUESTA PRIMARY KEY (NUM_APUESTA),
CONSTRAINT FK1_APUESTA FOREIGN KEY (COD_MANO) REFERENCES MANO(COD_MANO),
CONSTRAINT FK2_APUESTA FOREIGN KEY (CLAVE_RESULTADO) REFERENCES RESULTADO(CLAVE)
);

CREATE TABLE REALIZA (
NUM_APUESTA INT(10),
DNI VARCHAR(10),
CONSTRAINT PK_REALIZA PRIMARY KEY (NUM_APUESTA, DNI),
CONSTRAINT FK1_REALIZA FOREIGN KEY (NUM_APUESTA) REFERENCES APUESTA(NUM_APUESTA),
CONSTRAINT FK2_REALIZA FOREIGN KEY (DNI) REFERENCES JUGADOR(DNI)
);

CREATE TABLE ESTADISTICAS (
NUM_REG_ESTADISTICAS INT(10) NOT NULL,
DNI VARCHAR(10),
CONSTRAINT PK_EST PRIMARY KEY (NUM_REG_ESTADISTICAS),
CONSTRAINT FK1_EST FOREIGN KEY (DNI) REFERENCES JUGADOR(DNI)
);