ALTER SESSION SET "_oracle_script"=true;

CREATE USER dummy IDENTIFIED BY dummy;
GRANT CONNECT, RESOURCE, DBA TO dummy;

CREATE TABLE PERSONA (
    DNI VARCHAR2(10) NOT NULL,
    NOMBRE VARCHAR2(10),
    APELLIDOS VARCHAR2(10),
    CONSTRAINT PK_DNI PRIMARY KEY (DNI)
);

CREATE TABLE JUGADOR (
    DNI VARCHAR2(10),
    EDAD NUMBER(10),
    SALDO NUMBER(10),
    ANIO_REGISTRO DATE,
    CONSTRAINT PK_JUGADOR PRIMARY KEY (DNI),
    CONSTRAINT FK1_JUGADOR FOREIGN KEY (DNI) REFERENCES PERSONA(DNI),
    CONSTRAINT CHK_EDAD_JUGADOR CHECK (EDAD >= 18),
    CONSTRAINT CHK_SALDO CHECK (SALDO >= 0)
);

CREATE TABLE MESA (
    COD_MESA NUMBER(10) NOT NULL,
    UBICACION VARCHAR2(10),
    TIPO VARCHAR2(10),
    CAPACIDAD NUMBER(10),
    CONSTRAINT PK_MESA PRIMARY KEY (COD_MESA),
    CONSTRAINT CHK_CAPACIDAD CHECK (CAPACIDAD > 0)
);

CREATE TABLE CRUPIER (
    DNI VARCHAR2(10),
    TURNO NUMBER(10),
    EXP_CRUPIER VARCHAR2(10),
    COD_MESA NUMBER(10),
    CONSTRAINT PK_CRUPIER PRIMARY KEY (DNI),
    CONSTRAINT FKCRUPIER1 FOREIGN KEY (DNI) REFERENCES PERSONA(DNI),
    CONSTRAINT FKCRUPIER2 FOREIGN KEY (COD_MESA) REFERENCES MESA(COD_MESA)
);

CREATE TABLE BARAJA (
    REF_BARAJA NUMBER(10),
    NUM_CARTAS NUMBER(10),
    CONSTRAINT PK_BARAJA PRIMARY KEY (REF_BARAJA),
    CONSTRAINT CHK_NUM_CARTAS CHECK (NUM_CARTAS IN (40, 52))
);

CREATE TABLE RESULTADO (
    CLAVE VARCHAR2(10) NOT NULL,
    TIPO VARCHAR2(10),
    GANANCIA NUMBER(10) NOT NULL,
    CONSTRAINT PK_RESULTADO PRIMARY KEY (CLAVE),
    CONSTRAINT CHK_GANANCIA CHECK (GANANCIA >= 0)
);

CREATE TABLE PARTIDA (
    NUM_PARTIDA NUMBER(10) NOT NULL,
    FECHA_PARTIDA DATE,
    REF_BARAJA NUMBER(10) NOT NULL,
    CLAVE_RESULTADO VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_PARTIDA PRIMARY KEY (NUM_PARTIDA),
    CONSTRAINT FK1_PARTIDA FOREIGN KEY (REF_BARAJA) REFERENCES BARAJA(REF_BARAJA),
    CONSTRAINT FK2_PARTIDA FOREIGN KEY (CLAVE_RESULTADO) REFERENCES RESULTADO(CLAVE)
);

CREATE TABLE JUEGA (
    DNI VARCHAR2(10) NOT NULL,
    NUM_PARTIDA NUMBER(10),
    CONSTRAINT PK_JUEGA PRIMARY KEY (DNI, NUM_PARTIDA),
    CONSTRAINT FK_JUEGA1 FOREIGN KEY (DNI) REFERENCES PERSONA(DNI),
    CONSTRAINT FK_JUEGA2 FOREIGN KEY (NUM_PARTIDA) REFERENCES PARTIDA(NUM_PARTIDA)
);

CREATE TABLE MANO (
    COD_MANO NUMBER(10),
    ESTADO VARCHAR2(10),
    PUNTAJE NUMBER(10),
    CONSTRAINT PK_MANO PRIMARY KEY (COD_MANO)
);

CREATE TABLE CARTAS (
    REF_BARAJA NUMBER(10) NOT NULL,
    COD_MANO NUMBER(10),
    VALOR_CARTA NUMBER(10),
    CONSTRAINT PK_CARTAS PRIMARY KEY (REF_BARAJA, COD_MANO, VALOR_CARTA),
    CONSTRAINT FK1_CARTAS FOREIGN KEY (REF_BARAJA) REFERENCES BARAJA(REF_BARAJA),
    CONSTRAINT FK2_CARTAS FOREIGN KEY (COD_MANO) REFERENCES MANO(COD_MANO)
);

CREATE TABLE APUESTA (
    NUM_APUESTA NUMBER(10) NOT NULL,
    MONTO NUMBER(10),
    CLAVE_RESULTADO VARCHAR2(10),
    COD_MANO NUMBER(10),
    CONSTRAINT PK_APUESTA PRIMARY KEY (NUM_APUESTA),
    CONSTRAINT FK1_APUESTA FOREIGN KEY (COD_MANO) REFERENCES MANO(COD_MANO),
    CONSTRAINT FK2_APUESTA FOREIGN KEY (CLAVE_RESULTADO) REFERENCES RESULTADO(CLAVE),
    CONSTRAINT CHK_MONTO CHECK (MONTO > 0)
);

CREATE TABLE REALIZA (
    NUM_APUESTA NUMBER(10),
    DNI VARCHAR2(10),
    CONSTRAINT PK_REALIZA PRIMARY KEY (NUM_APUESTA, DNI),
    CONSTRAINT FK1_REALIZA FOREIGN KEY (NUM_APUESTA) REFERENCES APUESTA(NUM_APUESTA),
    CONSTRAINT FK2_REALIZA FOREIGN KEY (DNI) REFERENCES JUGADOR(DNI)
);

CREATE TABLE ESTADISTICAS (
    NUM_REG_ESTADISTICAS NUMBER(10) NOT NULL,
    DNI VARCHAR2(10),
    CONSTRAINT PK_EST PRIMARY KEY (NUM_REG_ESTADISTICAS),
    CONSTRAINT FK1_EST FOREIGN KEY (DNI) REFERENCES JUGADOR(DNI)
);

INSERT INTO PERSONA VALUES ('111A', 'Mario', 'Lopez');
INSERT INTO PERSONA VALUES ('222B', 'Laura', 'Perez');

INSERT INTO JUGADOR VALUES ('111A', 22, 500, SYSDATE);
INSERT INTO JUGADOR VALUES ('222B', 30, 300, SYSDATE);

INSERT INTO MESA VALUES (1, 'Sala1', 'Poker', 6);

INSERT INTO CRUPIER VALUES ('222B', 1, 'Alta', 1);

INSERT INTO BARAJA VALUES (10, 52);

INSERT INTO RESULTADO VALUES ('GANA', 'Victoria', 200);
INSERT INTO RESULTADO VALUES ('PIERDE', 'Derrota', 0);

INSERT INTO PARTIDA VALUES (100, SYSDATE, 10, 'GANA');

INSERT INTO MANO VALUES (50, 'Activa', 18);

INSERT INTO APUESTA VALUES (900, 50, 'GANA', 50);

INSERT INTO REALIZA VALUES (900, '111A');

DELETE FROM APUESTA
WHERE NUM_APUESTA = 900;
