CREATE TABLE PERSONA(
DNI VARCHAR (10) NOT NULL,
NOMBRE VARCHAR (100) NOT NULL,
APELLIDOS VARCHAR (100) NOT NULL,
CONSTRAINT PK_PERSONA PRIMARY KEY (DNI)
);

CREATE TABLE JUGADOR(
DNI VARCHAR (10) NOT NULL,
EDAD VARCHAR (10),
SALDO VARCHAR (10),
ANIO_REGISTRO DATE,
CONSTRAINT PK_JUGADOR PRIMARY KEY (DNI),
CONSTRAINT FK_JUGADOR_PERSONA FOREIGN KEY (DNI) REFERENCES PERSONA(DNI)
);

CREATE TABLE MESA(
COD_MESA INT NOT NULL,
UBICACION VARCHAR (100),
TIPO VARCHAR (100),
CAPACIDAD INT,
CONSTRAINT PK_MESA PRIMARY KEY (COD_MESA)
);

CREATE TABLE CRUPIER(
DNI VARCHAR (10) NOT NULL,
TURNO INT,
EXP_CRUPIER VARCHAR (10),
COD_MESA INT,
CONSTRAINT PK_CRUPIER PRIMARY KEY (DNI),
CONSTRAINT FK1_CRUPIER_PERSONA FOREIGN KEY (DNI) REFERENCES PERSONA(DNI),
CONSTRAINT FK2_CRUPIER_MESA FOREIGN KEY (COD_MESA) REFERENCES MESA(COD_MESA)
);

CREATE TABLE BARAJA(
REF_BARAJA INT NOT NULL,
NUM_CARTAS INT,
CONSTRAINT PK_BARAJA PRIMARY KEY (REF_BARAJA)
);

CREATE TABLE RESULTADO(
CLAVE_RESULTADO VARCHAR (10) NOT NULL,
TIPO VARCHAR (10) NOT NULL,
GANANCIA INT NOT NULL,
CONSTRAINT PK_RESULTADO PRIMARY KEY (CLAVE_RESULTADO)
);

CREATE TABLE PARTIDA(
NUM_PARTIDA INT NOT NULL,
FECHA_PARTIDA DATE NOT NULL,
REF_BARAJA INT NOT NULL,
CLAVE_RESULTADO VARCHAR (10) NOT NULL,
CONSTRAINT PK_PARTIDA PRIMARY KEY (NUM_PARTIDA),
CONSTRAINT FK1_PARTIDA_BARAJA FOREIGN KEY (REF_BARAJA) REFERENCES BARAJA(REF_BARAJA),
CONSTRAINT FK2_PARTIDA_RESULTADO FOREIGN KEY (CLAVE_RESULTADO) REFERENCES RESULTADO(CLAVE_RESULTADO)
);

CREATE TABLE JUEGA(
DNI VARCHAR (10) NOT NULL,
NUM_PARTIDA INT NOT NULL,
CONSTRAINT PK_JUEGA PRIMARY KEY (DNI),
CONSTRAINT FK1_JUEGA_PERSONA FOREIGN KEY (DNI) REFERENCES PERSONA(DNI),
CONSTRAINT FK2_JUEGA_PARTIDA FOREIGN KEY (NUM_PARTIDA) REFERENCES PARTIDA(NUM_PARTIDA)
);

CREATE TABLE MANO(
COD_MANO VARCHAR (10) NOT NULL,
ESTADO VARCHAR (10),
PUNTAJE INT,
CONSTRAINT PK_MANI PRIMARY KEY (COD_MANO)
);

CREATE TABLE CARTAS(
REF_BARAJA INT NOT NULL,
COD_MANO VARCHAR (10) NOT NULL,
VALOR_CARTA INT NOT NULL,
CONSTRAINT PK_CARTAS PRIMARY KEY (REF_BARAJA,COD_MANO,VALOR_CARTA),
CONSTRAINT FK1_CARTAS_BARAJA FOREIGN KEY (REF_BARAJA) REFERENCES BARAJA(REF_BARAJA),
CONSTRAINT FK2_CARTAS_MANO FOREIGN KEY (COD_MANO) REFERENCES MANO(COD_MANO)
);

CREATE TABLE APUESTA(
NUM_APUESTA INT NOT NULL,
MONTO VARCHAR (100),
CLAVE_RESULTADO VARCHAR (10) NOT NULL,
COD_MANO VARCHAR (10),
CONSTRAINT PK_APUESTA PRIMARY KEY (NUM_APUESTA),
CONSTRAINT FK1_APUESTA_MANO FOREIGN KEY (COD_MANO) REFERENCES MANO(COD_MANO),
CONSTRAINT FK2_APUESTA_RESULTADO FOREIGN KEY (CLAVE_RESULTADO) REFERENCES RESULTADO(CLAVE_RESULTADO)
);

CREATE TABLE REALIZA(
NUM_APUESTA INT NOT NULL,
DNI VARCHAR (10) NOT NULL,
CONSTRAINT PK_REALIZA PRIMARY KEY (NUM_APUESTA,DNI),
CONSTRAINT FK1_REALIZA_APUESTA FOREIGN KEY (NUM_APUESTA) REFERENCES APUESTA(NUM_APUESTA),
CONSTRAINT FK2_REALIZA_JUGADOR FOREIGN KEY (DNI) REFERENCES JUGADOR(DNI)

);

CREATE TABLE ESTADISTICA(
NUM_REG_ESTADISTICAS INT (10) NOT NULL,
DNI VARCHAR (10),
CONSTRAINT PK_ESTADISTICA PRIMARY KEY (NUM_REG_ESTADISTICAS),
CONSTRAINT FK1_ESTADISTICA_JUGADOR FOREIGN KEY (DNI) REFERENCES JUGADOR(DNI)
);