
CREATE TABLE INSTITUTO
(COD_INST NUMBER(5),
NOMBRE VARCHAR2(10),
HORAAPERTURA DATE,
HORACIERRE DATE,
CONSTRAINT PK_INSTITUTO PRIMARY KEY (COD_INST)
);

CREATE TABLE PERSONA
(DNI VARCHAR2(9),
COD_INST NUMBER(5),
CONSTRAINT PK_PERSONA PRIMARY KEY (DNI),
CONSTRAINT FK_PERSONA FOREIGN KEY (COD_INST) REFERENCES INSTITUTO(COD_INST)
);

CREATE TABLE EMPLEADO
(DNI VARCHAR2(9),
NSS NUMBER(20),
NOMBRE VARCHAR2(10),
APELLIDOS VARCHAR2(10),
FECHANACIMIENTO DATE,
SALARIO NUMBER(5),
NUM_CUENTA_BANC VARCHAR(24),
CONSTRAINT PK_EMPLEADO PRIMARY KEY (DNI),
CONSTRAINT FK_EMPLEADO FOREIGN KEY (DNI) REFERENCES PERSONA(DNI)
);

CREATE TABLE DEPARTAMENTO
(COD_DEP NUMBER(10),
NOMBRE VARCHAR2(10),
CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (COD_DEP)
);

CREATE TABLE CURSO
(NCURSO NUMBER(10),
NUM_ALUMN NUMBER(10),
DNI VARCHAR2(9),
CONSTRAINT PK_CURSO PRIMARY KEY (NCURSO),
CONSTRAINT FK_CURSO FOREIGN KEY (DNI) REFERENCES PERSONA(DNI)
);

CREATE TABLE ESTUDIANTES
(DNI VARCHAR2(9),
COD_FICHA NUMBER(10),
NOMBRE VARCHAR2(10),
APELLIDOS VARCHAR2(10),
GENERO VARCHAR2(10),
FECHANACIMIENTO DATE,
REPETIDOR CHAR(2),
NCURSO NUMBER(10),
CONSTRAINT PK_ESTUDIANTES PRIMARY KEY (DNI),
CONSTRAINT FK_ESTUDIANTES FOREIGN KEY (DNI) REFERENCES PERSONA(DNI),
CONSTRAINT FK2_ESTUDIANTES FOREIGN KEY (NCURSO) REFERENCES CURSO(NCURSO)
);

CREATE TABLE PERSONAL_MANTENIMIENTO
(DNI VARCHAR2(9),
HORARIO DATE,
CONSTRAINT PK_PM PRIMARY KEY (DNI),
CONSTRAINT FK_PM FOREIGN KEY (DNI) REFERENCES PERSONA(DNI)
);

CREATE TABLE DOCENTE
(DNI VARCHAR2(9),
DIRECTOR CHAR(2),
COD_DEP NUMBER(10),
CONSTRAINT PK_DOCENTE PRIMARY KEY (DNI),
CONSTRAINT FK_DOCENTE FOREIGN KEY (DNI) REFERENCES PERSONA(DNI),
CONSTRAINT FK2_DOCENTE FOREIGN KEY (COD_DEP) REFERENCES DEPARTAMENTO(COD_DEP)
);

CREATE TABLE AULA
(COD_AULA NUMBER(10),
NOMBRE VARCHAR2(10),
CAP_MAX NUMBER(10),
NCURSO NUMBER(10),
CONSTRAINT PK_AULA PRIMARY KEY (COD_AULA),
CONSTRAINT FK_AULA FOREIGN KEY (NCURSO) REFERENCES CURSO(NCURSO)
);

CREATE TABLE ASIGNATURA
(COD_ASIG NUMBER(10),
NOMBRE VARCHAR2(10),
COD_DEP NUMBER(10),
CONSTRAINT PK_ASIGNATURA PRIMARY KEY (COD_ASIG),
CONSTRAINT FK_ASIGNATURA FOREIGN KEY (COD_DEP) REFERENCES DEPARTAMENTO(COD_DEP)
);

CREATE TABLE CURSA
(DNI VARCHAR2(9),
COD_ASIG NUMBER(10),
NOTAFINAL NUMBER(4,2),
CONSTRAINT PK_CURSA PRIMARY KEY (DNI, COD_ASIG),
CONSTRAINT FK_CURSA FOREIGN KEY (DNI) REFERENCES ESTUDIANTES(DNI),
CONSTRAINT FK2_CURSA FOREIGN KEY (COD_ASIG) REFERENCES ASIGNATURA(COD_ASIG)
);

CREATE TABLE DA
(DNI VARCHAR2(9),
COD_ASIG NUMBER(10),
CONSTRAINT PK_DA PRIMARY KEY (DNI, COD_ASIG),
CONSTRAINT FK_DA FOREIGN KEY (DNI) REFERENCES DOCENTE(DNI),
CONSTRAINT FK2_DA FOREIGN KEY (COD_ASIG) REFERENCES ASIGNATURA(COD_ASIG)
);

ALTER TABLE ESTUDIANTES ADD CONSTRAINT CHK_ESTUDIANTES CHECK (REGEXP_LIKE(DNI, '^[0-9]{8}[A-Z]$'));

ALTER TABLE ESTUDIANTES ADD CONSTRAINT CHK_REPETIDOR CHECK (REPETIDOR IN ('Si', 'No'));

ALTER TABLE EMPLEADO ADD CONSTRAINT UQ_EMPLEADO UNIQUE (NSS);

ALTER TABLE EMPLEADO ADD CONSTRAINT UQ2_EMPLEADO UNIQUE (NUM_CUENTA_BANC);

ALTER TABLE INSTITUTO MODIFY COD_INST NOT NULL;

ALTER TABLE INSTITUTO ADD CONSTRAINT CHK_INSTITUTO CHECK (HORACIERRE > HORAAPERTURA);

ALTER TABLE CURSA ADD CONSTRAINT CHK_CURSA CHECK (NOTAFINAL BETWEEN 0 AND 10);

ALTER TABLE EMPLEADO ADD CONSTRAINT CHK_EMPLEADO CHECK (REGEXP_LIKE(NSS, '^[0-9]{12}$'));

ALTER TABLE ESTUDIANTES ADD CONSTRAINT CHK2_ESTUDIANTE CHECK (GENERO IN ('M', 'F'));



INSERT INTO INSTITUTO (COD_INST, NOMBRE, HORAAPERTURA, HORACIERRE) 
VALUES (1, 'InstiSur', TO_DATE('08:00', 'HH24:MI'), TO_DATE('22:00', 'HH24:MI'));

INSERT INTO PERSONA (DNI, COD_INST) VALUES ('12345678Z', 1);
INSERT INTO PERSONA (DNI, COD_INST) VALUES ('87654321X', 1);

INSERT INTO EMPLEADO (DNI, NSS, NOMBRE, APELLIDOS, FECHANACIMIENTO, SALARIO, NUM_CUENTA_BANC)
VALUES ('12345678Z', 123456789012, 'Ana', 'Garcia', TO_DATE('1985-05-10', 'YYYY-MM-DD'), 2500, 'ES1234567890123456789012');

INSERT INTO DEPARTAMENTO (COD_DEP, NOMBRE) VALUES (10, 'Sistemas');

INSERT INTO CURSO (NCURSO, NUM_ALUMN, DNI) VALUES (1, 30, '12345678Z');

INSERT INTO ESTUDIANTES (DNI, COD_FICHA, NOMBRE, APELLIDOS, GENERO, FECHANACIMIENTO, REPETIDOR, NCURSO)
VALUES ('87654321X', 101, 'Marcos', 'Perez', 'M', TO_DATE('2005-10-20', 'YYYY-MM-DD'), 'No', 1);

INSERT INTO ASIGNATURA (COD_ASIG, NOMBRE, COD_DEP) VALUES (500, 'BD', 10);

INSERT INTO CURSA (DNI, COD_ASIG, NOTAFINAL) VALUES ('87654321X', 500, 8.5);

COMMIT;

/*
RESTRICCIONES ADICIONALES:
1. CHECK (SALARIO > 1200): Garantizar un salario base mínimo para todos los empleados del centro.
2. CHECK (CAP_MAX > 0): Asegurar que todas las aulas dadas de alta tengan una capacidad positiva.
3. UNIQUE (NOMBRE): Impedir la creación de departamentos con nombres duplicados.

ENUNCIADOS DML:
1. INSERT: Dar de alta un nuevo docente con DNI '99999999R' asignándolo al departamento de 'Sistemas'.
2. UPDATE: Incrementar en un 10% el salario de los empleados que pertenezcan al instituto 'InstiSur'.
3. DELETE: Eliminar de la tabla CURSA las matrículas de alumnos que tengan una nota inferior a 1.0.
*/

