CREATE DATABASE enunciadoclasesql


CREATE TABLE INSTITUTO
(COD_INST INT(5) NOT NULL,
NOMBRE VARCHAR(10),
HORAAPERTURA DATE,
HORACIERRE DATE,
CONSTRAINT PK_INSTITUTO PRIMARY KEY (COD_INST)
);

CREATE TABLE PERSONA
(DNI VARCHAR(9),
COD_INST INT(5),
CONSTRAINT PK_PERSONA PRIMARY KEY (DNI),
CONSTRAINT FK_PERSONA FOREIGN KEY (COD_INST) REFERENCES INSTITUTO(COD_INST)
);

CREATE TABLE EMPLEADO
(DNI VARCHAR(9),
NSS INT(20),
NOMBRE VARCHAR(10),
APELLIDOS VARCHAR(10),
FECHANACIMIENTO DATE,
SALARIO INT(5),
NUM_CUENTA_BANC VARCHAR(24),
CONSTRAINT PK_EMPLEADO PRIMARY KEY (DNI),
CONSTRAINT FK_EMPLEADO FOREIGN KEY (DNI) REFERENCES PERSONA(DNI)
);

CREATE TABLE DEPARTAMENTO
(COD_DEP INT(10),
NOMBRE VARCHAR(10),
CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (COD_DEP)
);

CREATE TABLE CURSO
(NCURSO INT(10),
NUM_ALUMN INT(10),
DNI VARCHAR(9),
CONSTRAINT PK_CURSO PRIMARY KEY (NCURSO),
CONSTRAINT FK_CURSO FOREIGN KEY (DNI) REFERENCES PERSONA(DNI)
);

CREATE TABLE ESTUDIANTES
(DNI VARCHAR(9),
COD_FICHA INT(10),
NOMBRE VARCHAR(10),
APELLIDOS VARCHAR(10),
GENERO VARCHAR(10),
FECHANACIMIENTO DATE,
REPETIDOR CHAR(2),
NCURSO INT(10),
CONSTRAINT PK_ESTUDIANTES PRIMARY KEY (DNI),
CONSTRAINT FK_ESTUDIANTES FOREIGN KEY (DNI) REFERENCES PERSONA(DNI),
CONSTRAINT FK2_ESTUDIANTES FOREIGN KEY (NCURSO) REFERENCES CURSO(NCURSO)
);

CREATE TABLE PERSONAL_MANTENIMIENTO
(DNI VARCHAR(9),
HORARIO DATE,
CONSTRAINT PK_PM PRIMARY KEY (DNI),
CONSTRAINT FK_PM FOREIGN KEY (DNI) REFERENCES PERSONA(DNI)
);

CREATE TABLE DOCENTE
(DNI VARCHAR(9),
DIRECTOR CHAR(2),
COD_DEP INT(10),
CONSTRAINT PK_DOCENTE PRIMARY KEY (DNI),
CONSTRAINT FK_DOCENTE FOREIGN KEY (DNI) REFERENCES PERSONA(DNI),
CONSTRAINT FK2_DOCENTE FOREIGN KEY (COD_DEP) REFERENCES DEPARTAMENTO(COD_DEP)
);

CREATE TABLE AULA
(COD_AULA INT(10),
NOMBRE VARCHAR(10),
CAP_MAX INT(10),
NCURSO INT(10),
CONSTRAINT PK_AULA PRIMARY KEY (COD_AULA),
CONSTRAINT FK_AULA FOREIGN KEY (NCURSO) REFERENCES CURSO(NCURSO)
);

CREATE TABLE ASIGNATURA
(COD_ASIG INT(10),
NOMBRE VARCHAR(10),
COD_DEP INT(10),
CONSTRAINT PK_ASIGNATURA PRIMARY KEY (COD_ASIG),
CONSTRAINT FK_ASIGNATURA FOREIGN KEY (COD_DEP) REFERENCES DEPARTAMENTO(COD_DEP)
);

CREATE TABLE CURSA
(DNI VARCHAR(9),
COD_ASIG INT(10),
NOTAFINAL DECIMAL(4,2),
CONSTRAINT PK_CURSA PRIMARY KEY (DNI, COD_ASIG),
CONSTRAINT FK_CURSA FOREIGN KEY (DNI) REFERENCES ESTUDIANTES(DNI),
CONSTRAINT FK2_CURSA FOREIGN KEY (COD_ASIG) REFERENCES ASIGNATURA(COD_ASIG)
);

CREATE TABLE DA
(DNI VARCHAR(9),
COD_ASIG INT(10),
CONSTRAINT PK_DA PRIMARY KEY (DNI, COD_ASIG),
CONSTRAINT FK_DA FOREIGN KEY (DNI) REFERENCES DOCENTE(DNI),
CONSTRAINT FK2_DA FOREIGN KEY (COD_ASIG) REFERENCES ASIGNATURA(COD_ASIG)
);

ALTER TABLE ESTUDIANTES ADD CONSTRAINT CHK_ESTUDIANTES CHECK (REGEXP_LIKE(DNI, '^[0-9]{8}[A-Z]$'));

ALTER TABLE ESTUDIANTES ADD CONSTRAINT CHK_REPETIDOR CHECK (REPETIDOR IN ('Si', 'No'));

ALTER TABLE EMPLEADO ADD CONSTRAINT UQ_EMPLEADO UNIQUE (NSS);

ALTER TABLE EMPLEADO ADD CONSTRAINT UQ2_EMPLEADO UNIQUE (NUM_CUENTA_BANC);

ALTER TABLE INSTITUTO ADD CONSTRAINT CHK_INSTITUTO CHECK (HORACIERRE > HORAAPERTURA);

ALTER TABLE CURSA ADD CONSTRAINT CHK_CURSA CHECK (NOTAFINAL BETWEEN 0 AND 10);

ALTER TABLE EMPLEADO ADD CONSTRAINT CHK_EMPLEADO CHECK (REGEXP_LIKE(NSS, '^[0-9]{12}$'));

ALTER TABLE ESTUDIANTES ADD CONSTRAINT CHK2_ESTUDIANTE CHECK (GENERO IN ('M', 'F'));
