INSERT INTO VIAJE(COD, ESTADO_CONVOY, MIN_DEMORA) VALUES('1', 'OPERATIVO', '10');
INSERT INTO BILLETE(COD, COD_VIAJE, METODO_PAGO, PRECIO, ASIENTO) VALUES('1', '1', 'EFECTIVO', '3', '23');
INSERT INTO PASAJERO(DNI, COD_BILLETE, COD_VIAJE, SEXO, NOMBRE, EDAD, INDICARDOR_ASISTENCIA) VALUES('12345678X', '1', '1', 'HOMBRE', 'PEPE', '25', 'NO');
INSERT INTO AVALA(DNI_AVALA, DNI_AVALADO) VALUES('12345678X', '12345678X');
INSERT INTO COD_POSTALES(CIUDAD, COD_POSTAL) VALUES('SEVILLA', '41310');
INSERT INTO ESTACION(COD, COD_POSTAL, NUM_VIAS) VALUES('312', '41310', '12');
INSERT INTO ESTACION_CATEGORIA(COD_ESTACION, CATEGORIA) VALUES('312', 'VIAJEROS');
INSERT INTO REALIZAN(COD_ESTACION, COD_VIAJE) VALUES('312', '1');
INSERT INTO PERSONAL(DNI, NSS, NOMBRE, APELLIDOS, SALARIO_BASE, ANTIGUEDAD, COD_ESTACION) VALUES('23232323F', '23422342232', 'JOSE', 'LOPEZ', '1600', '5', '312');
INSERT INTO CONDUCTOR(DNI, LICENCIA, EXPERIENCIA) VALUES('23232323F', 'B', '10');
INSERT INTO VIGILANTE(DNI, EMPRESA_EXTERNA, NUMPLACA) VALUES('23232323F', 'RENFE', '56');
INSERT INTO ATENCION_AL_CLIENTE(DNI, PUESTO) VALUES('23232323F', 'OBJETOS PERDIDOS');
INSERT INTO ATENCION_AL_CLIENTE_IDIOMAS(DNI, IDIOMA_ADICIONAL) VALUES('23232323F', 'ALEMAN');
INSERT INTO RUTA(COD, DISTANCIA_TOTAL, VELOCIDAD_MAXIMA, COD_VIAJE) VALUES('5', '10', '100', '1');
INSERT INTO PARADA(COD_RUTA, COD, VIA_LLEGADA, TIEMPO_QUE_PERTENECE) VALUES('5', '8', '10', '50');
INSERT INTO TREN(MATRICULA, MODELO, FECHA_FAB) VALUES('1234QWS', 'MAGLEV', '10-FEB-2000');
INSERT INTO HACE(MATRICULA, COD_PARADA, COD_RUTA, DIA_SEMANA, HORA_SALIDA) VALUES('1234QWS', '8', '5', 'LUNES', '8');
INSERT INTO REVISION(COD_REVISION, FECHA, COSTE, TIPO_REPARACION, MATRICULA) VALUES('43', '07-OCT-2025', '300', 'CHASIS', '1234QWS');
INSERT INTO VAGONES(MATRICULA, NUM_BASTIDOR, CAPACIDAD) VALUES('1234QWS', '24', '150');
INSERT INTO VAGONES_SERVICIOS(MATRICULA, NUM_BASTIDOR, SERVICIOS)VALUES('1234QWS', '24', 'BAR');

/*Restricciones:
 *En los atributos de minutos, poner un valor maximo de 2.
 *En metodo de pago  solamente efectivo o tarjeta.
 *En sexo solamente hombre o mujer.
 *En edad el valor maximo que sea 122.
 *Indicador de asistencia, que sea solamente "Si" o "No"
 *En los DNI que el valor sea 8numeros y una letra mayuscula, todo seguido.
 *El codigo postal que sean maximo 5 caracteres.
 *En salario base el valor minimo debe ser el salario minimo de ese momento, actualmente es 1184 euros.
 *En las matriculas que sean maximo 12 digitos
 */